spring:
  application:
    name: GlobTrotter

  datasource:
    url: jdbc:postgresql://miyazapp.cbcoqks0yis3.us-east-1.rds.amazonaws.com:5432/postgres
    username: olawale
    password: Olawale22
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: globetrt
        format_sql: true

server:
  port: 4447

logging:
  level:
    org.springframework.security: DEBUG
